# Rechnernamen
meta.pc=22H0566
privat.pc=DESKTOP-3NCAR95
schmi.pc=DESKTOP-Q6O0UGB
test.pc=DESKTOP-LERLCJ6

# Logging Pfade
logpath.meta=C:\\Users\\TSZ\\Daten\\Java\\Applications\\app\\logs
logpath.privat = C:\\Users\\Privat\\Daten\\Java\\Applications\\app\\logs
logpath.schmi=C:\\Users\\schmi\\Daten\\Java\\Applications\\app\\logs
logpath.test=C:\\Users\\test\\Daten\\Java\\Applications\\app\\logs

# Sonstiges
error.host=Kein Computername definiert
